name: ebpv2
description: EBP Version 2.0 Flutter Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  dio: ^4.0.6
  url_launcher: ^6.0.4
  rxdart: ^0.27.0
  material_segmented_control: ^3.1.2
  cupertino_icons: ^1.0.2
  connectivity: ^3.0.4
  shared_preferences: ^2.0.5
  material_design_icons_flutter: ^3.2.3895
  intl: ^0.17.0
  cached_network_image: ^3.0.0
  rflutter_alert: ^2.0.4
  lottie: ^1.1.0
  flutter_svg: ^0.22.0
  carousel_slider: ^4.0.0
  visibility_detector: ^0.2.0
  flutter_spinkit: ^5.1.0
  jumio_mobile_sdk_flutter: ^3.9.2
  getwidget: ^2.0.4
  country_code_picker: ^2.0.2
  expansion_tile_card: ^2.0.0
  scroll_to_index: ^1.0.6
  path_provider: ^2.0.7
  image_picker: ^0.8.4+4
  flutter_html: any
  loader_overlay: ^2.0.4+3
  share_plus: ^3.0.4
  file_picker: ^4.2.7
  intl_phone_number_input: ^0.7.0+2
  firebase_messaging: ^11.2.3
  firebase_core: ^1.2.1
  firebase_analytics: any
  flutter_local_notifications: ^8.2.0
  open_file: ^3.2.1
  syncfusion_flutter_pdfviewer: ^19.4.38-beta
  iban: ^1.0.1
  phone_number: ^0.12.0+1
  image_gallery_saver: '^1.7.1'
  flip_card: ^0.6.0
  xml2json: ^5.3.2
  jiffy: ^5.0.0
  syncfusion_flutter_charts: ^19.4.40
  html2md: ^1.2.5
  gallery_saver: ^2.3.2
  barcode_scan2: ^4.2.0
  scan: ^1.6.0
  webview_flutter: ^3.0.4
  credit_card_validator: ^2.0.1
  cupertino_will_pop_scope: ^1.2.0
  qr_flutter: ^4.0.0
  native_pdf_renderer: ^4.0.1
  internet_connection_checker: ^0.0.1+3
  local_auth: ^1.1.11
  get_it: ^7.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/json/
    - assets/language/
    - assets/images/banner_1.jpg

  fonts:
    - family: FuturaStd
      fonts:
        - asset: assets/font/FuturaStd-Medium.ttf

    - family: PROXIMA_NOVA
      fonts:
        - asset: assets/font/proxima_nova/ProximaNova-Regular.otf

    - family: SF_UI_DISPLAY
      fonts:
            - asset: assets/font/sf_ui_display/sf-ui-display-medium-58646be638f96.otf

    - family: SF_UI_TEXT_REGULAR
      fonts:
            - asset: assets/font/sf_ui_text/SFUIText-Regular.ttf

    - family: SF_UI_TEXT_MEDIUM
      fonts:
            - asset: assets/font/sf_ui_text/SFUIText-Medium.ttf
